default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: quarterly
  skip: ["next-lint-website"]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: >
          (?x)(
            build|
            stubs|
            ^bot/templates/$|
            openassistant/templates|
            docs/docs/api/openapi\.json|
            scripts/postprocessing/regex_pii_detector\.py
          )
      - id: check-ast
      - id: check-yaml
        exclude: ^copilot/.*/addons/.*$
      - id: check-json
      - id: check-case-conflict
      - id: detect-private-key
      - id: fix-encoding-pragma
        args: [--remove]
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-byte-order-marker
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.263
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args:
          [
            --prose-wrap=always,
            --write,
            --ignore-path=./website/.prettierignore,
          ]

  - repo: local
    hooks:
      - id: check-english-only
        name: Check for English-only content
        entry: python check_english_only.py
        language: python
        types: [text]
        exclude: |
          (?x)(
            ^docs/locales/|
            ^.*/locale/|
            \.po$|
            \.mo$|
            ^data/|
            ^tests/fixtures/
          )

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-merge-conflict

exclude: '^\.env$'
